### PR TITLE
WIP: Trim blocks

### PR DESCRIPTION
**Pull request by FSMaxB**
In this pull request, I'm working on implementing the `trim_blocks` feature discussed in #9.

This is a work in progress, I'm only creating this pull request to be able to get feedback. Note that I will probably use `git rebase` from time to time, so be aware of that if you intend to fetch this branch.

### CODE REVIEW

**Comment by FSMaxB** [comment]
I should now have reached the milestone of feature parity with slt2 v1.0 (with the exception of some of the variable scoping).

**Comment by FSMaxB** [comment]
Cyclic inclusion detection is now working.

Road ahead:
* [ ] implement a `trim_blocks` option
* [ ] implement an option for relative include paths (or as default?)
* [ ] write unit tests, once it is decided which one to use
* [ ] update the readme
* [ ] do some final performance, readability and/or structural improvements

**Comment by henix** [comment]
I think you are doing too much for this. Anyway, thanks for your work! Although I prefer to refactor the code on my own. Your code is a good reference. I have noticed some good improvements over original code:

* `start_tag` and `end_tag` need to be escaped
* `read_entire_file` helper function

**Comment by FSMaxB** [comment]
Hm. Now that I've almost entirely rewritten everything, I can just as well finished what I've started.

If you decide to include my code, tell me what I should change, so I can adapt it. Otherwise I'll probably just fork slt2 for the time being and continue to watch your approach on refactoring slt2.

**Comment by FSMaxB** [comment]
Just an info if anyone is interested. I'm done forking slt2 under the name [liluat](https://github.com/FSMaxB/liluat), you can take a look if you're interested.

**Comment by henix** [comment]
Greak work! I will continue to improve slt2

**Pull request closed without merging**
